---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kubernetes-runners
  namespace: actions
spec:
  template:
    spec:
      organization: GithubRunnersTestOrg
      labels:
        - my-custom-runner-1
      env: []
